:toc:

== CardVisualize
叠加上去的元素有其唯一key，同一key重复设置效果为替换

* CardVisualize.SetIcon(card, string icon, x, y, width, height, overwriteKey?)

按名称将图片icon叠加到card上

icon名作为key

* CardVisualize.SetIconByCard(card, iconCard, x, y, width, height, overwriteKey?)

将iconCard的图标叠加到card上

card的对象名作为key(不同inGame卡牌直接不同)

* CardVisualize.SetText(card, localKey, x, y, width, height, overwriteKey?)

将本地化字符串键localKey(找不到对应项则直接把key的内容显示上去)叠加到card上

文本自动缩放到区域最大，不提供字体大小选项

localKey作为key

* CardVisualize.ClearIcon(card)

清除所有叠加的图片，并删除存储数据

* CardVisualize.RegCardHoverEvent(string uuid, fun(CardAccessBridge card, TooltipText tooltip) function)

注册卡牌OnHover回调，可以修改tooltip对象

** TooltipText

  public string TooltipTitle
  public string TooltipContent
  public int Priority
  public float NormalizedHoldTime
  public string HoldText

* 已知问题
====
* 由于多张卡牌重新生成后排序并不固定，所以持久性存储不一定能生效。
* 只有一张卡在一格的情况下，重开游戏或重进env都能保持icon的叠加状态
====

== ZGameUI
* ZGameUI.CreateWindow(name, string backgroundSprite?, float x = 0, float y = 0, float width = 100, float height = 100):UIWindow

创建UIWindow

=== CommonUIBase
* methods:
** AddOnClick(Action) // 请自行确保删除时的action和添加时一致(保留action引用)
** RemoveOnClick(Action)
** Destroy() // 删除界面对象
** Reset() // 重置界面状态
** FullInit() // 初始化界面(更新状态变更)
** SetPosition(float x, float y)
** SetSize(float width, float height)
* fields:
** Name : string
** Size : UnityEngine.Vector2
** LocalPosition : UnityEngine.Vector2
** Rotation : float
** LocalScale : UnityEngine.Vector2

=== UIImage : CommonUIBase
* methods:
** SetColor(float r, float g, float b)
** SetAlpha(float a)
* fields:
** Color : UnityEngine.Color
** Sprite : string

=== UICard : UIImage
相当于俩Image组合，前景和背景，共享Color设置

* methods:
** SetSubPosition(float x, float y)
** SetSubSize(float width, float height)
* fields:
** SubSpriteName : string

=== UIText : CommonUIBase
* fields:
** FontSize : float
** Text : string
** TextAlignment : TextAlignmentOptions

=== UIButton : UIImage
相当于Image上组合一个Text，常规按钮结构

* methods:
** SetSubPosition(float x, float y)
** SetSubSize(float width, float height)
* fields:
** FontSize : float
** Label : string
** TextAlignment : TextAlignmentOptions

=== UIPanel : UIImage
用来容纳其他组件，支持展示个背景

* fields:
** GridLayoutEnable : bool
** GridSizeHorizontal : bool
** GridSizeVertical : bool
* methods:
** UIPanel AddPanel(string name, string image, float x = 0, float y = 0, float width = 100, float height = 100)
** UIImage AddImage(string name, string image, float x = 0, float y = 0, float width = 100, float height = 100)
** UICard AddCard(string name, string image, string subImage, float x = 0, float y = 0, float width = 100, float height = 100)
** UIText AddText(string name, string text, float fontSize, float x = 0, float y = 0, float width = 100, float height = 100)
** UIButton AddButton(string name, string image, string label, float fontSize, float x = 0, float y = 0, float width = 100, float height = 100)
** UIScrollPanel AddScrollPanel(string name, bool horizontalScroll, float x = 0, float y = 0, float width = 100, float height = 100, float scrollSpeed = 1)
** UIScrollRect AddScrollRect(string name, bool horizontalScroll, float x = 0, float y = 0, float width = 100, float height = 100, float scrollSpeed = 1, bool mask = false)

=== UIWindow : UIPanel
可以打开关闭，所有ui的基础

* methods:
** Open()
** Close()

=== UIScrollPanel : UIPanel
双方向滚动面板，按住左ctrl使滚动方向旋转90%，不支持mask

* fields:
** HorizontalScrollEnable : bool
** VerticalScrollEnable : bool
** ScrollSpeed : float

=== UIScrollRect : UIScrollPanel
双方向滚动区域，支持mask

* fields:
** Mask : bool

=== Enums

==== Enums.TextAlignmentOptions

  TopLeft = 257
  Top = 258
  TopRight = 260
  TopJustified = 264
  TopFlush = 272
  TopGeoAligned = 288
  Left = 513
  Center = 514
  Right = 516
  Justified = 520
  Flush = 528
  CenterGeoAligned = 544
  BottomLeft = 1025
  Bottom = 1026
  BottomRight = 1028
  BottomJustified = 1032
  BottomFlush = 1040
  BottomGeoAligned = 1056
  BaselineLeft = 2049
  Baseline = 2050
  BaselineRight = 2052
  BaselineJustified = 2056
  BaselineFlush = 2064
  BaselineGeoAligned = 2080
  MidlineLeft = 4097
  Midline = 4098
  MidlineRight = 4100
  MidlineJustified = 4104
  MidlineFlush = 4112
  MidlineGeoAligned = 4128
  CaplineLeft = 8193
  Capline = 8194
  CaplineRight = 8196
  CaplineJustified = 8200
  CaplineFlush = 8208
  CaplineGeoAligned = 8224
  Converted = 65535

== ZGameSystem

=== ZGameSystem.RegisterCardTp(string uuid, Action<CardAccessBridge> action)

对uuid对应的卡牌注册每帧执行的函数，不可取消

=== ZGameSystem.RegisterCardOnClick(string uuid, Func<CardAccessBridge, bool> action)

对uuid对应的卡牌注册点击卡牌时执行的函数，返回true表示已处理该点击事件并阻断点击事件的继续传播，不可取消

== 注
* 参数名后跟?代表该参数可选，默认值为空
* 参数名后跟=代表该参数可选，默认值为=的值
