:toc:

== CardVisualize
叠加上去的元素有其唯一key，同一key重复设置效果为替换

* CardVisualize.SetIcon(card, string icon, x, y, width, height, overwriteKey?)

按名称将图片icon叠加到card上

icon名作为key

* CardVisualize.SetIconByCard(card, iconCard, x, y, width, height, overwriteKey?)

将iconCard的图标叠加到card上

card的对象名作为key(不同inGame卡牌直接不同)

* CardVisualize.SetText(card, localKey, x, y, width, height, overwriteKey?)

将本地化字符串键localKey(找不到对应项则直接把key的内容显示上去)叠加到card上

文本自动缩放到区域最大，不提供字体大小选项

localKey作为key

* CardVisualize.ClearIcon(card)

清除所有叠加的图片，并删除存储数据

* 已知问题
====
* 由于多张卡牌重新生成后排序并不固定，所以持久性存储不一定能生效。
* 只有一张卡在一格的情况下，重开游戏或重进env都能保持icon的叠加状态
====

== ZGameUI
* ZGameUI.CreateWindow(name, string backgroundSprite?, float x = 0, float y = 0, float width = 100, float height = 100):UIWindow

创建UIWindow

=== CommonUIBase
* methods:
** AddOnClick(Action) // 请自行确保删除时的action和添加时一致(保留action引用)
** RemoveOnClick(Action)
** Destroy() // 删除界面对象
** Reset() // 重置界面状态
** FullInit() // 初始化界面(更新状态变更)
* fields:
** Name : string
** Size : UnityEngine.Vector2
** LocalPosition : UnityEngine.Vector2
** Rotation : float
** LocalScale : UnityEngine.Vector2

=== UIImage : CommonUIBase
* methods:
** SetColor(float r, float g, float b)
** SetAlpha(float a)
* fields:
** Color : UnityEngine.Color
** Sprite : string

=== UIText : CommonUIBase
* fields:
** FontSize : float
** Text : string

=== UIPanel : UIImage
用来容纳其他组件，支持展示个背景

* methods:
** UIPanel AddPanel(string name, string image, float x = 0, float y = 0, float width = 100, float height = 100)
** UIImage AddImage(string name, string image, float x = 0, float y = 0, float width = 100, float height = 100)
** UIText AddText(string name, string text, float fontSize, float x = 0, float y = 0, float width = 100, float height = 100)
** UIScrollPanel AddScrollPanel(string name, bool horizontalScroll, float x = 0, float y = 0, float width = 100, float height = 100, float scrollSpeed = 1)
** UIScrollRect AddScrollRect(string name, bool horizontalScroll, float x = 0, float y = 0, float width = 100, float height = 100, float scrollSpeed = 1, bool mask = false)

=== UIWindow : UIPanel
可以打开关闭，所有ui的基础

* methods:
** Open()
** Close()

=== UIScrollPanel : UIPanel
双方向滚动面板，按住左ctrl使滚动方向旋转90%，不支持mask

* fields:
** HorizontalScrollEnable : bool
** VerticalScrollEnable : bool
** ScrollSpeed : float

=== UIScrollRect : UIScrollPanel
双方向滚动区域，支持mask

* fields:
** Mask : bool

== 注
* 参数名后跟?代表该参数可选，默认值为空
* 参数名后跟=代表该参数可选，默认值为=的值
